Niyaz dev12/issue5
Iraq-RBC-Capstones-2021/capstone-react-libvery pull request #23
Opened 2021-10-08 15:52 UTC by Niyaz-Dev12

Responsive Footer created with placeholder data for social links and contact-us info
Closes #5

2021-10-08 16:13 UTC, RawandDev requested changes

2021-10-08 16:13 UTC, RawandDev commented on src/components/Footer.jsx
> +                <Link to={HOME_ROUTE} className="mx-5">
Please make these look like a link in the UI. Because people wouldn't know this is a link unless they hover over it.

2021-10-08 16:23 UTC, RawandDev commented
I see the whole logo is an svg. You could download only the book as svg then write Libvery. It would be easier to align I guess since the alignment of Libvery and Contact us is not the same
![Untitled](https://user-images.githubusercontent.com/82733587/136590868-817dd72c-0a71-4377-826e-8dc9cb8b6346.png)
.

2021-10-08 16:59 UTC, Niyaz-Dev12 commented on src/components/Footer.jsx
> +                <Link to={HOME_ROUTE} className="mx-5">
i added the hover color effect, as for making it obvious it's a link underline may work but i haven't seen footers with that

2021-10-09 14:18 UTC, MuhannedNoman approved these changes
Hey @Niyaz-Dev12 nice work here LGTM. Feel free to merge.

2021-10-09 14:38 UTC, RawandDev approved these changes
LGTM

2021-10-09 17:45 UTC, merged