Home page
Iraq-RBC-Capstones-2021/capstone-react-libvery pull request #32
Opened 2021-10-12 14:43 UTC by ZhraaBaharAluloom

2021-10-12 15:16 UTC, MuhannedNoman commented
> 
> 
> _No description provided._

Can you use PRs template here so that we can get information faster!

2021-10-12 15:20 UTC, MuhannedNoman requested changes
@ZhraaBaharAluloom Hey nice work here, left you some comments to go through and let me know what you think!

2021-10-12 15:20 UTC, MuhannedNoman commented on src/pages/HomeSlides.jsx
> +const HomeSlides = () => {
Where will the book data come from? Can we have a TODO item here to remind us?

2021-10-12 15:20 UTC, MuhannedNoman commented on src/pages/HomeSlides.jsx
> +    <img
Can we use [next/image](https://nextjs.org/docs/api-reference/next/image) here?

2021-10-12 17:30 UTC, ZhraaBaharAluloom commented
> > _No description provided._
> 
> Can you use PRs template here so that we can get information faster!

Sure, sorry forgot that

2021-10-12 18:08 UTC, ZhraaBaharAluloom commented on src/pages/HomeSlides.jsx
> +    <img
> Can we use [next/image](https://nextjs.org/docs/api-reference/next/image) here?

No

2021-10-14 08:19 UTC, MuhannedNoman approved these changes
LGTM, just implement the suggested changes and feel free to merge.

2021-10-14 08:19 UTC, MuhannedNoman commented on src/components/style.css
> +.react-3d-carousel .slider-container .slider-right div {
Just move this file next to the HomeSlider where it is used.

2021-10-14 08:19 UTC, MuhannedNoman commented on src/components/HomeSlides.jsx
> +  // TODO: get the books images as a prop from the parent (Home)
Why not set it now? Have an array of objects be passed from the parent and loop through it here.

2021-10-15 04:32 UTC, merged