fix styles
Iraq-RBC-Capstones-2021/capstone-react-libvery pull request #52
Opened 2021-10-17 14:25 UTC by ZhraaBaharAluloom

Fixed update book details, contact and edit image modals

2021-10-17 17:48 UTC, RawandDev requested changes
Well done Zahra, They look really nice.
I have added two comments to improve a bit.

2021-10-17 17:48 UTC, RawandDev commented on src/components/ContactModal.jsx
> +          className="flex flex-col  items-center    text-primary bg-black rounded-lg p-10  relative font-sans md:w-96 text-sm sm:text-lg"
Not sure if this is something important to mention but I see some extra double and triple spaces which is not necessary.
Before `text-primary` there are triple spaces and some other places there are two.

2021-10-17 17:48 UTC, RawandDev commented on src/components/EditImageModal.jsx
> +                  // className="bg-primary rounded-full cursor-pointer"
There are three comments. Can you remove them?

2021-10-18 10:17 UTC, MuhannedNoman approved these changes
Feel free to merge after seeing Rawand's comments.

2021-10-19 16:50 UTC, ZhraaBaharAluloom commented on src/components/ContactModal.jsx
> +          className="flex flex-col  items-center    text-primary bg-black rounded-lg p-10  relative font-sans md:w-96 text-sm sm:text-lg"
> Not sure if this is something important to mention but I see some extra double and triple spaces which is not necessary. Before `text-primary` there are triple spaces and some other places there are two.

No it's not sth important to mention 🙂, but i'll do it

2021-10-20 07:28 UTC, RawandDev approved these changes
LGTM

2021-10-21 12:46 UTC, merged